apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-app.fullname" . }}-config
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
data:
  ENVIRONMENT: "production"
  APP_NAME: "Flask Hello World"
  LOG_LEVEL: "INFO"
